services:
  postgres:
    image: postgres:16.8
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  mongo:
    image: mongo:8.0.5
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "27017:27017"
    networks:
      - app_network
    command: ["mongod", "--bind_ip_all"]

  app:
    build: .
    container_name: app
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - postgres
      - mongo
    networks:
      - app_network
    command: ["sh", "-c", "sleep 15 && python main.py"]  

networks:
  app_network:
    driver: bridge
